apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${name}-binding-deployment
  namespace: ${namespace}    
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ${name}-binding-deployment
      app.kubernetes.io/instance: ${name}-binding-deployment
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ${name}-binding-deployment
        app.kubernetes.io/instance: ${name}-binding-deployment
    spec:
      containers:
        - name: ${name}-binding-deployment
          image: ubuntu:latest
          # Just spin & wait forever
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "while true; do sleep 30; done;" ]
